{
 "title": "Observability - Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Geral", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tempo médio TEF",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (evento) ((rate(app_request_duration_seconds_sum{outcome=\"SUCCESS\"}[1m])/rate(app_request_duration_seconds_count{outcome=\"SUCCESS\"}[1m]))*1000)",
     "legendFormat": "{{evento}}"
    }
   ]
  },
  {
   "title": "# Requests",
   "type": "stat",
   "gridPos": { "h": 13, "w": 8, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (evento, status) (increase(app_request_duration_seconds_count[1m]))",
     "legendFormat": "{{evento}} {{status}}"
    }
   ]
  },
  {
   "title": "Distribuição dos erros",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (increase(app_request_duration_seconds_count{evento=\"simulacao\",status!=\"200\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (evento) (increase(app_request_duration_seconds_count{evento=~\"simulacao|efetivacao\",status!=\"200\"}[1m]))/sum by (evento) (increase(app_request_duration_seconds_count{evento=~\"simulacao|efetivacao\"}[1m]))*100) ",
     "legendFormat": "{{evento}}"
    }
   ]
  },
  { "title": "TEF - Golden Signas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latência",
   "type": "timeseries",
   "description": "Tempo médio de resposta das transações com sucesso (status code = 200) nos últimos 5 minutos",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, avg by (evento) (rate(app_request_duration_seconds_sum{evento=~\"simulacao|efetivacao\",status=\"200\"}[1m])/rate(app_request_duration_seconds_count{evento=~\"simulacao|efetivacao\",status=\"200\"}[1m])))",
     "legendFormat": "{{evento}}"
    }
   ]
  },
  {
   "title": "Tráfego",
   "type": "graph",
   "description": "Quantidade de transações a cada 5 minutos",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum by (evento, status) (increase(app_request_duration_seconds_count[1m]))",
     "legendFormat": "{{evento}} - {{status}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros",
   "type": "graph",
   "description": "Proporção de requisições com erro",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (evento) (increase(app_request_duration_seconds_count{evento=~\"simulacao|efetivacao\",status!=\"200\"}[1m]))/sum by (evento) (increase(app_request_duration_seconds_count{evento=~\"simulacao|efetivacao\"}[1m])))",
     "legendFormat": "{{evento}}"
    }
   ]
  },
  {
   "title": "Saturação",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_lag)",
     "legendFormat": "Consumer Lag do Tópico {{topic}}"
    }
   ]
  },
  { "title": "Dependencias - Golden Signals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Latência",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (app) (rate(app_request_duration_milliseconds_sum[1m])/rate(app_request_duration_milliseconds_count[1m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Tráfego",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (operacao) (increase(app_request_duration_milliseconds_count[1m]))",
     "legendFormat": "{{operacao}}"
    }
   ]
  },
  {
   "title": "Errors nas Dependencias",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\nsum by (app) (increase(app_message_publish_total{resultado=\"ERRO\"}[1m]))/sum by (app) (increase(app_message_publish_total{resultado=~\"SUCESSO|ERRO\"}[1m]))*100)",
     "legendFormat": "{{app}}"
    }
   ]
  }
 ]
}