{
 "title": "Health Check",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "TEF - Health Check - Qtde",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cTef_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cTef_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cTef_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "TEF - Health Check - Tempo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cTef_miliseconds_sum / hca_kafka_producer_Gm4cTef_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cTef_miliseconds_sum / hca_redis_connection_notcluster_Gm4cTef_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cTef_miliseconds_sum / hca_h2_query_Gm4cTef_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Senha - Health Check - Qtde",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cSenha_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cSenha_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cSenha_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Senha - Health Check - Tempo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cSenha_miliseconds_sum / hca_kafka_producer_Gm4cSenha_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cSenha_miliseconds_sum / hca_redis_connection_notcluster_Gm4cSenha_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cSenha_miliseconds_sum / hca_h2_query_Gm4cSenha_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Limite - Health Check - Qtde",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cLimite_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cLimite_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cLimite_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Limite - Health Check - Tempo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cLimite_miliseconds_sum / hca_kafka_producer_Gm4cLimite_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cLimite_miliseconds_sum / hca_redis_connection_notcluster_Gm4cLimite_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cLimite_miliseconds_sum / hca_h2_query_Gm4cLimite_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Conta - Health Check - Qtde",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cLimite_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cLimite_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cLimite_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  },
  {
   "title": "Conta - Health Check - Tempo",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "hca_kafka_producer_Gm4cConta_miliseconds_sum / hca_kafka_producer_Gm4cConta_miliseconds_count",
     "legendFormat": "Kafka"
    },
    {
     "expr": "hca_redis_connection_notcluster_Gm4cConta_miliseconds_sum / hca_redis_connection_notcluster_Gm4cConta_miliseconds_count",
     "legendFormat": "Redis"
    },
    {
     "expr": "hca_h2_query_Gm4cConta_miliseconds_sum / hca_h2_query_Gm4cConta_miliseconds_count",
     "legendFormat": "H2"
    }
   ]
  }
 ]
}