{
 "title": "Observability - Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latência",
   "type": "graph",
   "description": "Tempo médio de resposta das transações com sucesso (status code = 200) nos últimos 5 minutos",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_sum{job=\"tef\",uri=~\"/tef/simulacao|/tef/efetivacao\",status=\"200\"}[5m]))\r\n/\r\nsum by (uri) (increase(http_server_requests_seconds_count{job=\"tef\",uri=~\"/tef/simulacao|/tef/efetivacao\",status=\"200\"}[5m]))\r",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Tráfego",
   "type": "graph",
   "description": "Quantidade de transações a cada 5 minutos",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (uri,outcome) (increase(http_server_requests_seconds_count{job=\"tef\",uri=~\"/tef/simulacao|/tef/efetivacao\"}[5m]))\r",
     "legendFormat": "{{uri}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "Taxa de Erros",
   "type": "graph",
   "description": "Proporção de requisições com erro",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\nsum by (uri) (increase(http_server_requests_seconds_count{job=\"tef\",uri=~\"/tef/simulacao|/tef/efetivacao\",status!=\"200\"}[5m]))\r\n/\nsum by (uri) (increase(http_server_requests_seconds_count{job=\"tef\",uri=~\"/tef/simulacao|/tef/efetivacao\"}[5m]))\r\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Saturação",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumer_records_lag_records)",
     "legendFormat": "Consumer Lag do Tópico {{topic}}"
    }
   ]
  }
 ]
}