/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gm4c.conta;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ContaCorrente extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5193830428513705054L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ContaCorrente\",\"namespace\":\"com.gm4c.conta\",\"fields\":[{\"name\":\"id_simulacao\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"id da simulacao\"},{\"name\":\"agencia_origem\",\"type\":\"int\",\"doc\":\"Codigo da agencia de origem\"},{\"name\":\"conta_origem\",\"type\":\"int\",\"doc\":\"Codigo da conta de origem\"},{\"name\":\"dv_origem\",\"type\":\"int\",\"doc\":\"Dac da conta de origem\"},{\"name\":\"agencia_destino\",\"type\":\"int\",\"doc\":\"Codigo da agencia de destino\"},{\"name\":\"conta_destino\",\"type\":\"int\",\"doc\":\"Codigo da conta de destino\"},{\"name\":\"dv_destino\",\"type\":\"int\",\"doc\":\"dac da conta de destino\"},{\"name\":\"aprovacao_conta_origem\",\"type\":\"boolean\",\"doc\":\"se a conta origem foi ou nao aprovada\"},{\"name\":\"motivo_conta_origem\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"codigo de retorno da conta origem\"},{\"name\":\"aprovacao_conta_destino\",\"type\":\"boolean\",\"doc\":\"se a conta origem foi ou nao aprovada\"},{\"name\":\"motivo_conta_destino\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"codigo de retorno da conta origem\"},{\"name\":\"evento\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"evento\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ContaCorrente> ENCODER =
      new BinaryMessageEncoder<ContaCorrente>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ContaCorrente> DECODER =
      new BinaryMessageDecoder<ContaCorrente>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ContaCorrente> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ContaCorrente> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ContaCorrente>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ContaCorrente to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ContaCorrente from a ByteBuffer. */
  public static ContaCorrente fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** id da simulacao */
   private java.lang.String id_simulacao;
  /** Codigo da agencia de origem */
   private int agencia_origem;
  /** Codigo da conta de origem */
   private int conta_origem;
  /** Dac da conta de origem */
   private int dv_origem;
  /** Codigo da agencia de destino */
   private int agencia_destino;
  /** Codigo da conta de destino */
   private int conta_destino;
  /** dac da conta de destino */
   private int dv_destino;
  /** se a conta origem foi ou nao aprovada */
   private boolean aprovacao_conta_origem;
  /** codigo de retorno da conta origem */
   private java.lang.String motivo_conta_origem;
  /** se a conta origem foi ou nao aprovada */
   private boolean aprovacao_conta_destino;
  /** codigo de retorno da conta origem */
   private java.lang.String motivo_conta_destino;
  /** evento */
   private java.lang.String evento;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ContaCorrente() {}

  /**
   * All-args constructor.
   * @param id_simulacao id da simulacao
   * @param agencia_origem Codigo da agencia de origem
   * @param conta_origem Codigo da conta de origem
   * @param dv_origem Dac da conta de origem
   * @param agencia_destino Codigo da agencia de destino
   * @param conta_destino Codigo da conta de destino
   * @param dv_destino dac da conta de destino
   * @param aprovacao_conta_origem se a conta origem foi ou nao aprovada
   * @param motivo_conta_origem codigo de retorno da conta origem
   * @param aprovacao_conta_destino se a conta origem foi ou nao aprovada
   * @param motivo_conta_destino codigo de retorno da conta origem
   * @param evento evento
   */
  public ContaCorrente(java.lang.String id_simulacao, java.lang.Integer agencia_origem, java.lang.Integer conta_origem, java.lang.Integer dv_origem, java.lang.Integer agencia_destino, java.lang.Integer conta_destino, java.lang.Integer dv_destino, java.lang.Boolean aprovacao_conta_origem, java.lang.String motivo_conta_origem, java.lang.Boolean aprovacao_conta_destino, java.lang.String motivo_conta_destino, java.lang.String evento) {
    this.id_simulacao = id_simulacao;
    this.agencia_origem = agencia_origem;
    this.conta_origem = conta_origem;
    this.dv_origem = dv_origem;
    this.agencia_destino = agencia_destino;
    this.conta_destino = conta_destino;
    this.dv_destino = dv_destino;
    this.aprovacao_conta_origem = aprovacao_conta_origem;
    this.motivo_conta_origem = motivo_conta_origem;
    this.aprovacao_conta_destino = aprovacao_conta_destino;
    this.motivo_conta_destino = motivo_conta_destino;
    this.evento = evento;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id_simulacao;
    case 1: return agencia_origem;
    case 2: return conta_origem;
    case 3: return dv_origem;
    case 4: return agencia_destino;
    case 5: return conta_destino;
    case 6: return dv_destino;
    case 7: return aprovacao_conta_origem;
    case 8: return motivo_conta_origem;
    case 9: return aprovacao_conta_destino;
    case 10: return motivo_conta_destino;
    case 11: return evento;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id_simulacao = (java.lang.String)value$; break;
    case 1: agencia_origem = (java.lang.Integer)value$; break;
    case 2: conta_origem = (java.lang.Integer)value$; break;
    case 3: dv_origem = (java.lang.Integer)value$; break;
    case 4: agencia_destino = (java.lang.Integer)value$; break;
    case 5: conta_destino = (java.lang.Integer)value$; break;
    case 6: dv_destino = (java.lang.Integer)value$; break;
    case 7: aprovacao_conta_origem = (java.lang.Boolean)value$; break;
    case 8: motivo_conta_origem = (java.lang.String)value$; break;
    case 9: aprovacao_conta_destino = (java.lang.Boolean)value$; break;
    case 10: motivo_conta_destino = (java.lang.String)value$; break;
    case 11: evento = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id_simulacao' field.
   * @return id da simulacao
   */
  public java.lang.String getIdSimulacao() {
    return id_simulacao;
  }

  /**
   * Sets the value of the 'id_simulacao' field.
   * id da simulacao
   * @param value the value to set.
   */
  public void setIdSimulacao(java.lang.String value) {
    this.id_simulacao = value;
  }

  /**
   * Gets the value of the 'agencia_origem' field.
   * @return Codigo da agencia de origem
   */
  public java.lang.Integer getAgenciaOrigem() {
    return agencia_origem;
  }

  /**
   * Sets the value of the 'agencia_origem' field.
   * Codigo da agencia de origem
   * @param value the value to set.
   */
  public void setAgenciaOrigem(java.lang.Integer value) {
    this.agencia_origem = value;
  }

  /**
   * Gets the value of the 'conta_origem' field.
   * @return Codigo da conta de origem
   */
  public java.lang.Integer getContaOrigem() {
    return conta_origem;
  }

  /**
   * Sets the value of the 'conta_origem' field.
   * Codigo da conta de origem
   * @param value the value to set.
   */
  public void setContaOrigem(java.lang.Integer value) {
    this.conta_origem = value;
  }

  /**
   * Gets the value of the 'dv_origem' field.
   * @return Dac da conta de origem
   */
  public java.lang.Integer getDvOrigem() {
    return dv_origem;
  }

  /**
   * Sets the value of the 'dv_origem' field.
   * Dac da conta de origem
   * @param value the value to set.
   */
  public void setDvOrigem(java.lang.Integer value) {
    this.dv_origem = value;
  }

  /**
   * Gets the value of the 'agencia_destino' field.
   * @return Codigo da agencia de destino
   */
  public java.lang.Integer getAgenciaDestino() {
    return agencia_destino;
  }

  /**
   * Sets the value of the 'agencia_destino' field.
   * Codigo da agencia de destino
   * @param value the value to set.
   */
  public void setAgenciaDestino(java.lang.Integer value) {
    this.agencia_destino = value;
  }

  /**
   * Gets the value of the 'conta_destino' field.
   * @return Codigo da conta de destino
   */
  public java.lang.Integer getContaDestino() {
    return conta_destino;
  }

  /**
   * Sets the value of the 'conta_destino' field.
   * Codigo da conta de destino
   * @param value the value to set.
   */
  public void setContaDestino(java.lang.Integer value) {
    this.conta_destino = value;
  }

  /**
   * Gets the value of the 'dv_destino' field.
   * @return dac da conta de destino
   */
  public java.lang.Integer getDvDestino() {
    return dv_destino;
  }

  /**
   * Sets the value of the 'dv_destino' field.
   * dac da conta de destino
   * @param value the value to set.
   */
  public void setDvDestino(java.lang.Integer value) {
    this.dv_destino = value;
  }

  /**
   * Gets the value of the 'aprovacao_conta_origem' field.
   * @return se a conta origem foi ou nao aprovada
   */
  public java.lang.Boolean getAprovacaoContaOrigem() {
    return aprovacao_conta_origem;
  }

  /**
   * Sets the value of the 'aprovacao_conta_origem' field.
   * se a conta origem foi ou nao aprovada
   * @param value the value to set.
   */
  public void setAprovacaoContaOrigem(java.lang.Boolean value) {
    this.aprovacao_conta_origem = value;
  }

  /**
   * Gets the value of the 'motivo_conta_origem' field.
   * @return codigo de retorno da conta origem
   */
  public java.lang.String getMotivoContaOrigem() {
    return motivo_conta_origem;
  }

  /**
   * Sets the value of the 'motivo_conta_origem' field.
   * codigo de retorno da conta origem
   * @param value the value to set.
   */
  public void setMotivoContaOrigem(java.lang.String value) {
    this.motivo_conta_origem = value;
  }

  /**
   * Gets the value of the 'aprovacao_conta_destino' field.
   * @return se a conta origem foi ou nao aprovada
   */
  public java.lang.Boolean getAprovacaoContaDestino() {
    return aprovacao_conta_destino;
  }

  /**
   * Sets the value of the 'aprovacao_conta_destino' field.
   * se a conta origem foi ou nao aprovada
   * @param value the value to set.
   */
  public void setAprovacaoContaDestino(java.lang.Boolean value) {
    this.aprovacao_conta_destino = value;
  }

  /**
   * Gets the value of the 'motivo_conta_destino' field.
   * @return codigo de retorno da conta origem
   */
  public java.lang.String getMotivoContaDestino() {
    return motivo_conta_destino;
  }

  /**
   * Sets the value of the 'motivo_conta_destino' field.
   * codigo de retorno da conta origem
   * @param value the value to set.
   */
  public void setMotivoContaDestino(java.lang.String value) {
    this.motivo_conta_destino = value;
  }

  /**
   * Gets the value of the 'evento' field.
   * @return evento
   */
  public java.lang.String getEvento() {
    return evento;
  }

  /**
   * Sets the value of the 'evento' field.
   * evento
   * @param value the value to set.
   */
  public void setEvento(java.lang.String value) {
    this.evento = value;
  }

  /**
   * Creates a new ContaCorrente RecordBuilder.
   * @return A new ContaCorrente RecordBuilder
   */
  public static com.gm4c.conta.ContaCorrente.Builder newBuilder() {
    return new com.gm4c.conta.ContaCorrente.Builder();
  }

  /**
   * Creates a new ContaCorrente RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ContaCorrente RecordBuilder
   */
  public static com.gm4c.conta.ContaCorrente.Builder newBuilder(com.gm4c.conta.ContaCorrente.Builder other) {
    return new com.gm4c.conta.ContaCorrente.Builder(other);
  }

  /**
   * Creates a new ContaCorrente RecordBuilder by copying an existing ContaCorrente instance.
   * @param other The existing instance to copy.
   * @return A new ContaCorrente RecordBuilder
   */
  public static com.gm4c.conta.ContaCorrente.Builder newBuilder(com.gm4c.conta.ContaCorrente other) {
    return new com.gm4c.conta.ContaCorrente.Builder(other);
  }

  /**
   * RecordBuilder for ContaCorrente instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ContaCorrente>
    implements org.apache.avro.data.RecordBuilder<ContaCorrente> {

    /** id da simulacao */
    private java.lang.String id_simulacao;
    /** Codigo da agencia de origem */
    private int agencia_origem;
    /** Codigo da conta de origem */
    private int conta_origem;
    /** Dac da conta de origem */
    private int dv_origem;
    /** Codigo da agencia de destino */
    private int agencia_destino;
    /** Codigo da conta de destino */
    private int conta_destino;
    /** dac da conta de destino */
    private int dv_destino;
    /** se a conta origem foi ou nao aprovada */
    private boolean aprovacao_conta_origem;
    /** codigo de retorno da conta origem */
    private java.lang.String motivo_conta_origem;
    /** se a conta origem foi ou nao aprovada */
    private boolean aprovacao_conta_destino;
    /** codigo de retorno da conta origem */
    private java.lang.String motivo_conta_destino;
    /** evento */
    private java.lang.String evento;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gm4c.conta.ContaCorrente.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id_simulacao)) {
        this.id_simulacao = data().deepCopy(fields()[0].schema(), other.id_simulacao);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agencia_origem)) {
        this.agencia_origem = data().deepCopy(fields()[1].schema(), other.agencia_origem);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.conta_origem)) {
        this.conta_origem = data().deepCopy(fields()[2].schema(), other.conta_origem);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dv_origem)) {
        this.dv_origem = data().deepCopy(fields()[3].schema(), other.dv_origem);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.agencia_destino)) {
        this.agencia_destino = data().deepCopy(fields()[4].schema(), other.agencia_destino);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.conta_destino)) {
        this.conta_destino = data().deepCopy(fields()[5].schema(), other.conta_destino);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dv_destino)) {
        this.dv_destino = data().deepCopy(fields()[6].schema(), other.dv_destino);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.aprovacao_conta_origem)) {
        this.aprovacao_conta_origem = data().deepCopy(fields()[7].schema(), other.aprovacao_conta_origem);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.motivo_conta_origem)) {
        this.motivo_conta_origem = data().deepCopy(fields()[8].schema(), other.motivo_conta_origem);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.aprovacao_conta_destino)) {
        this.aprovacao_conta_destino = data().deepCopy(fields()[9].schema(), other.aprovacao_conta_destino);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.motivo_conta_destino)) {
        this.motivo_conta_destino = data().deepCopy(fields()[10].schema(), other.motivo_conta_destino);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.evento)) {
        this.evento = data().deepCopy(fields()[11].schema(), other.evento);
        fieldSetFlags()[11] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ContaCorrente instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gm4c.conta.ContaCorrente other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id_simulacao)) {
        this.id_simulacao = data().deepCopy(fields()[0].schema(), other.id_simulacao);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agencia_origem)) {
        this.agencia_origem = data().deepCopy(fields()[1].schema(), other.agencia_origem);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.conta_origem)) {
        this.conta_origem = data().deepCopy(fields()[2].schema(), other.conta_origem);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dv_origem)) {
        this.dv_origem = data().deepCopy(fields()[3].schema(), other.dv_origem);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.agencia_destino)) {
        this.agencia_destino = data().deepCopy(fields()[4].schema(), other.agencia_destino);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.conta_destino)) {
        this.conta_destino = data().deepCopy(fields()[5].schema(), other.conta_destino);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dv_destino)) {
        this.dv_destino = data().deepCopy(fields()[6].schema(), other.dv_destino);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.aprovacao_conta_origem)) {
        this.aprovacao_conta_origem = data().deepCopy(fields()[7].schema(), other.aprovacao_conta_origem);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.motivo_conta_origem)) {
        this.motivo_conta_origem = data().deepCopy(fields()[8].schema(), other.motivo_conta_origem);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.aprovacao_conta_destino)) {
        this.aprovacao_conta_destino = data().deepCopy(fields()[9].schema(), other.aprovacao_conta_destino);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.motivo_conta_destino)) {
        this.motivo_conta_destino = data().deepCopy(fields()[10].schema(), other.motivo_conta_destino);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.evento)) {
        this.evento = data().deepCopy(fields()[11].schema(), other.evento);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'id_simulacao' field.
      * id da simulacao
      * @return The value.
      */
    public java.lang.String getIdSimulacao() {
      return id_simulacao;
    }

    /**
      * Sets the value of the 'id_simulacao' field.
      * id da simulacao
      * @param value The value of 'id_simulacao'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setIdSimulacao(java.lang.String value) {
      validate(fields()[0], value);
      this.id_simulacao = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id_simulacao' field has been set.
      * id da simulacao
      * @return True if the 'id_simulacao' field has been set, false otherwise.
      */
    public boolean hasIdSimulacao() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id_simulacao' field.
      * id da simulacao
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearIdSimulacao() {
      id_simulacao = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @return The value.
      */
    public java.lang.Integer getAgenciaOrigem() {
      return agencia_origem;
    }

    /**
      * Sets the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @param value The value of 'agencia_origem'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setAgenciaOrigem(int value) {
      validate(fields()[1], value);
      this.agencia_origem = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'agencia_origem' field has been set.
      * Codigo da agencia de origem
      * @return True if the 'agencia_origem' field has been set, false otherwise.
      */
    public boolean hasAgenciaOrigem() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearAgenciaOrigem() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @return The value.
      */
    public java.lang.Integer getContaOrigem() {
      return conta_origem;
    }

    /**
      * Sets the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @param value The value of 'conta_origem'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setContaOrigem(int value) {
      validate(fields()[2], value);
      this.conta_origem = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'conta_origem' field has been set.
      * Codigo da conta de origem
      * @return True if the 'conta_origem' field has been set, false otherwise.
      */
    public boolean hasContaOrigem() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearContaOrigem() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @return The value.
      */
    public java.lang.Integer getDvOrigem() {
      return dv_origem;
    }

    /**
      * Sets the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @param value The value of 'dv_origem'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setDvOrigem(int value) {
      validate(fields()[3], value);
      this.dv_origem = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dv_origem' field has been set.
      * Dac da conta de origem
      * @return True if the 'dv_origem' field has been set, false otherwise.
      */
    public boolean hasDvOrigem() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearDvOrigem() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @return The value.
      */
    public java.lang.Integer getAgenciaDestino() {
      return agencia_destino;
    }

    /**
      * Sets the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @param value The value of 'agencia_destino'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setAgenciaDestino(int value) {
      validate(fields()[4], value);
      this.agencia_destino = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'agencia_destino' field has been set.
      * Codigo da agencia de destino
      * @return True if the 'agencia_destino' field has been set, false otherwise.
      */
    public boolean hasAgenciaDestino() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearAgenciaDestino() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @return The value.
      */
    public java.lang.Integer getContaDestino() {
      return conta_destino;
    }

    /**
      * Sets the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @param value The value of 'conta_destino'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setContaDestino(int value) {
      validate(fields()[5], value);
      this.conta_destino = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'conta_destino' field has been set.
      * Codigo da conta de destino
      * @return True if the 'conta_destino' field has been set, false otherwise.
      */
    public boolean hasContaDestino() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearContaDestino() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'dv_destino' field.
      * dac da conta de destino
      * @return The value.
      */
    public java.lang.Integer getDvDestino() {
      return dv_destino;
    }

    /**
      * Sets the value of the 'dv_destino' field.
      * dac da conta de destino
      * @param value The value of 'dv_destino'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setDvDestino(int value) {
      validate(fields()[6], value);
      this.dv_destino = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'dv_destino' field has been set.
      * dac da conta de destino
      * @return True if the 'dv_destino' field has been set, false otherwise.
      */
    public boolean hasDvDestino() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'dv_destino' field.
      * dac da conta de destino
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearDvDestino() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'aprovacao_conta_origem' field.
      * se a conta origem foi ou nao aprovada
      * @return The value.
      */
    public java.lang.Boolean getAprovacaoContaOrigem() {
      return aprovacao_conta_origem;
    }

    /**
      * Sets the value of the 'aprovacao_conta_origem' field.
      * se a conta origem foi ou nao aprovada
      * @param value The value of 'aprovacao_conta_origem'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setAprovacaoContaOrigem(boolean value) {
      validate(fields()[7], value);
      this.aprovacao_conta_origem = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'aprovacao_conta_origem' field has been set.
      * se a conta origem foi ou nao aprovada
      * @return True if the 'aprovacao_conta_origem' field has been set, false otherwise.
      */
    public boolean hasAprovacaoContaOrigem() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'aprovacao_conta_origem' field.
      * se a conta origem foi ou nao aprovada
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearAprovacaoContaOrigem() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'motivo_conta_origem' field.
      * codigo de retorno da conta origem
      * @return The value.
      */
    public java.lang.String getMotivoContaOrigem() {
      return motivo_conta_origem;
    }

    /**
      * Sets the value of the 'motivo_conta_origem' field.
      * codigo de retorno da conta origem
      * @param value The value of 'motivo_conta_origem'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setMotivoContaOrigem(java.lang.String value) {
      validate(fields()[8], value);
      this.motivo_conta_origem = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'motivo_conta_origem' field has been set.
      * codigo de retorno da conta origem
      * @return True if the 'motivo_conta_origem' field has been set, false otherwise.
      */
    public boolean hasMotivoContaOrigem() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'motivo_conta_origem' field.
      * codigo de retorno da conta origem
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearMotivoContaOrigem() {
      motivo_conta_origem = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'aprovacao_conta_destino' field.
      * se a conta origem foi ou nao aprovada
      * @return The value.
      */
    public java.lang.Boolean getAprovacaoContaDestino() {
      return aprovacao_conta_destino;
    }

    /**
      * Sets the value of the 'aprovacao_conta_destino' field.
      * se a conta origem foi ou nao aprovada
      * @param value The value of 'aprovacao_conta_destino'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setAprovacaoContaDestino(boolean value) {
      validate(fields()[9], value);
      this.aprovacao_conta_destino = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'aprovacao_conta_destino' field has been set.
      * se a conta origem foi ou nao aprovada
      * @return True if the 'aprovacao_conta_destino' field has been set, false otherwise.
      */
    public boolean hasAprovacaoContaDestino() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'aprovacao_conta_destino' field.
      * se a conta origem foi ou nao aprovada
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearAprovacaoContaDestino() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'motivo_conta_destino' field.
      * codigo de retorno da conta origem
      * @return The value.
      */
    public java.lang.String getMotivoContaDestino() {
      return motivo_conta_destino;
    }

    /**
      * Sets the value of the 'motivo_conta_destino' field.
      * codigo de retorno da conta origem
      * @param value The value of 'motivo_conta_destino'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setMotivoContaDestino(java.lang.String value) {
      validate(fields()[10], value);
      this.motivo_conta_destino = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'motivo_conta_destino' field has been set.
      * codigo de retorno da conta origem
      * @return True if the 'motivo_conta_destino' field has been set, false otherwise.
      */
    public boolean hasMotivoContaDestino() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'motivo_conta_destino' field.
      * codigo de retorno da conta origem
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearMotivoContaDestino() {
      motivo_conta_destino = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'evento' field.
      * evento
      * @return The value.
      */
    public java.lang.String getEvento() {
      return evento;
    }

    /**
      * Sets the value of the 'evento' field.
      * evento
      * @param value The value of 'evento'.
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder setEvento(java.lang.String value) {
      validate(fields()[11], value);
      this.evento = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'evento' field has been set.
      * evento
      * @return True if the 'evento' field has been set, false otherwise.
      */
    public boolean hasEvento() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'evento' field.
      * evento
      * @return This builder.
      */
    public com.gm4c.conta.ContaCorrente.Builder clearEvento() {
      evento = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ContaCorrente build() {
      try {
        ContaCorrente record = new ContaCorrente();
        record.id_simulacao = fieldSetFlags()[0] ? this.id_simulacao : (java.lang.String) defaultValue(fields()[0]);
        record.agencia_origem = fieldSetFlags()[1] ? this.agencia_origem : (java.lang.Integer) defaultValue(fields()[1]);
        record.conta_origem = fieldSetFlags()[2] ? this.conta_origem : (java.lang.Integer) defaultValue(fields()[2]);
        record.dv_origem = fieldSetFlags()[3] ? this.dv_origem : (java.lang.Integer) defaultValue(fields()[3]);
        record.agencia_destino = fieldSetFlags()[4] ? this.agencia_destino : (java.lang.Integer) defaultValue(fields()[4]);
        record.conta_destino = fieldSetFlags()[5] ? this.conta_destino : (java.lang.Integer) defaultValue(fields()[5]);
        record.dv_destino = fieldSetFlags()[6] ? this.dv_destino : (java.lang.Integer) defaultValue(fields()[6]);
        record.aprovacao_conta_origem = fieldSetFlags()[7] ? this.aprovacao_conta_origem : (java.lang.Boolean) defaultValue(fields()[7]);
        record.motivo_conta_origem = fieldSetFlags()[8] ? this.motivo_conta_origem : (java.lang.String) defaultValue(fields()[8]);
        record.aprovacao_conta_destino = fieldSetFlags()[9] ? this.aprovacao_conta_destino : (java.lang.Boolean) defaultValue(fields()[9]);
        record.motivo_conta_destino = fieldSetFlags()[10] ? this.motivo_conta_destino : (java.lang.String) defaultValue(fields()[10]);
        record.evento = fieldSetFlags()[11] ? this.evento : (java.lang.String) defaultValue(fields()[11]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ContaCorrente>
    WRITER$ = (org.apache.avro.io.DatumWriter<ContaCorrente>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ContaCorrente>
    READER$ = (org.apache.avro.io.DatumReader<ContaCorrente>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
