/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.gm4c.tef;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Transferencia extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3794264417508668986L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Transferencia\",\"namespace\":\"com.gm4c.tef\",\"fields\":[{\"name\":\"evento\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"tipo do evento: simulacao, efeticacao, externo\"},{\"name\":\"agencia_origem\",\"type\":\"int\",\"doc\":\"Codigo da agencia de origem\"},{\"name\":\"conta_origem\",\"type\":\"int\",\"doc\":\"Codigo da conta de origem\"},{\"name\":\"dv_origem\",\"type\":\"int\",\"doc\":\"Dac da conta de origem\"},{\"name\":\"agencia_destino\",\"type\":\"int\",\"doc\":\"Codigo da agencia de destino\"},{\"name\":\"conta_destino\",\"type\":\"int\",\"doc\":\"Codigo da conta de destino\"},{\"name\":\"dv_destino\",\"type\":\"int\",\"doc\":\"dac da conta de destino\"},{\"name\":\"valor\",\"type\":\"float\",\"doc\":\"Valor da Transferencia\"},{\"name\":\"senha\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Senha para validar a transferencia\"},{\"name\":\"id_transacao\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Id da transacao\"},{\"name\":\"tipo_transacao\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Transferencia> ENCODER =
      new BinaryMessageEncoder<Transferencia>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Transferencia> DECODER =
      new BinaryMessageDecoder<Transferencia>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Transferencia> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Transferencia> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Transferencia>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Transferencia to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Transferencia from a ByteBuffer. */
  public static Transferencia fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** tipo do evento: simulacao, efeticacao, externo */
   private java.lang.String evento;
  /** Codigo da agencia de origem */
   private int agencia_origem;
  /** Codigo da conta de origem */
   private int conta_origem;
  /** Dac da conta de origem */
   private int dv_origem;
  /** Codigo da agencia de destino */
   private int agencia_destino;
  /** Codigo da conta de destino */
   private int conta_destino;
  /** dac da conta de destino */
   private int dv_destino;
  /** Valor da Transferencia */
   private float valor;
  /** Senha para validar a transferencia */
   private java.lang.String senha;
  /** Id da transacao */
   private java.lang.String id_transacao;
  /** Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC */
   private java.lang.String tipo_transacao;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Transferencia() {}

  /**
   * All-args constructor.
   * @param evento tipo do evento: simulacao, efeticacao, externo
   * @param agencia_origem Codigo da agencia de origem
   * @param conta_origem Codigo da conta de origem
   * @param dv_origem Dac da conta de origem
   * @param agencia_destino Codigo da agencia de destino
   * @param conta_destino Codigo da conta de destino
   * @param dv_destino dac da conta de destino
   * @param valor Valor da Transferencia
   * @param senha Senha para validar a transferencia
   * @param id_transacao Id da transacao
   * @param tipo_transacao Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
   */
  public Transferencia(java.lang.String evento, java.lang.Integer agencia_origem, java.lang.Integer conta_origem, java.lang.Integer dv_origem, java.lang.Integer agencia_destino, java.lang.Integer conta_destino, java.lang.Integer dv_destino, java.lang.Float valor, java.lang.String senha, java.lang.String id_transacao, java.lang.String tipo_transacao) {
    this.evento = evento;
    this.agencia_origem = agencia_origem;
    this.conta_origem = conta_origem;
    this.dv_origem = dv_origem;
    this.agencia_destino = agencia_destino;
    this.conta_destino = conta_destino;
    this.dv_destino = dv_destino;
    this.valor = valor;
    this.senha = senha;
    this.id_transacao = id_transacao;
    this.tipo_transacao = tipo_transacao;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return evento;
    case 1: return agencia_origem;
    case 2: return conta_origem;
    case 3: return dv_origem;
    case 4: return agencia_destino;
    case 5: return conta_destino;
    case 6: return dv_destino;
    case 7: return valor;
    case 8: return senha;
    case 9: return id_transacao;
    case 10: return tipo_transacao;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: evento = (java.lang.String)value$; break;
    case 1: agencia_origem = (java.lang.Integer)value$; break;
    case 2: conta_origem = (java.lang.Integer)value$; break;
    case 3: dv_origem = (java.lang.Integer)value$; break;
    case 4: agencia_destino = (java.lang.Integer)value$; break;
    case 5: conta_destino = (java.lang.Integer)value$; break;
    case 6: dv_destino = (java.lang.Integer)value$; break;
    case 7: valor = (java.lang.Float)value$; break;
    case 8: senha = (java.lang.String)value$; break;
    case 9: id_transacao = (java.lang.String)value$; break;
    case 10: tipo_transacao = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'evento' field.
   * @return tipo do evento: simulacao, efeticacao, externo
   */
  public java.lang.String getEvento() {
    return evento;
  }

  /**
   * Sets the value of the 'evento' field.
   * tipo do evento: simulacao, efeticacao, externo
   * @param value the value to set.
   */
  public void setEvento(java.lang.String value) {
    this.evento = value;
  }

  /**
   * Gets the value of the 'agencia_origem' field.
   * @return Codigo da agencia de origem
   */
  public java.lang.Integer getAgenciaOrigem() {
    return agencia_origem;
  }

  /**
   * Sets the value of the 'agencia_origem' field.
   * Codigo da agencia de origem
   * @param value the value to set.
   */
  public void setAgenciaOrigem(java.lang.Integer value) {
    this.agencia_origem = value;
  }

  /**
   * Gets the value of the 'conta_origem' field.
   * @return Codigo da conta de origem
   */
  public java.lang.Integer getContaOrigem() {
    return conta_origem;
  }

  /**
   * Sets the value of the 'conta_origem' field.
   * Codigo da conta de origem
   * @param value the value to set.
   */
  public void setContaOrigem(java.lang.Integer value) {
    this.conta_origem = value;
  }

  /**
   * Gets the value of the 'dv_origem' field.
   * @return Dac da conta de origem
   */
  public java.lang.Integer getDvOrigem() {
    return dv_origem;
  }

  /**
   * Sets the value of the 'dv_origem' field.
   * Dac da conta de origem
   * @param value the value to set.
   */
  public void setDvOrigem(java.lang.Integer value) {
    this.dv_origem = value;
  }

  /**
   * Gets the value of the 'agencia_destino' field.
   * @return Codigo da agencia de destino
   */
  public java.lang.Integer getAgenciaDestino() {
    return agencia_destino;
  }

  /**
   * Sets the value of the 'agencia_destino' field.
   * Codigo da agencia de destino
   * @param value the value to set.
   */
  public void setAgenciaDestino(java.lang.Integer value) {
    this.agencia_destino = value;
  }

  /**
   * Gets the value of the 'conta_destino' field.
   * @return Codigo da conta de destino
   */
  public java.lang.Integer getContaDestino() {
    return conta_destino;
  }

  /**
   * Sets the value of the 'conta_destino' field.
   * Codigo da conta de destino
   * @param value the value to set.
   */
  public void setContaDestino(java.lang.Integer value) {
    this.conta_destino = value;
  }

  /**
   * Gets the value of the 'dv_destino' field.
   * @return dac da conta de destino
   */
  public java.lang.Integer getDvDestino() {
    return dv_destino;
  }

  /**
   * Sets the value of the 'dv_destino' field.
   * dac da conta de destino
   * @param value the value to set.
   */
  public void setDvDestino(java.lang.Integer value) {
    this.dv_destino = value;
  }

  /**
   * Gets the value of the 'valor' field.
   * @return Valor da Transferencia
   */
  public java.lang.Float getValor() {
    return valor;
  }

  /**
   * Sets the value of the 'valor' field.
   * Valor da Transferencia
   * @param value the value to set.
   */
  public void setValor(java.lang.Float value) {
    this.valor = value;
  }

  /**
   * Gets the value of the 'senha' field.
   * @return Senha para validar a transferencia
   */
  public java.lang.String getSenha() {
    return senha;
  }

  /**
   * Sets the value of the 'senha' field.
   * Senha para validar a transferencia
   * @param value the value to set.
   */
  public void setSenha(java.lang.String value) {
    this.senha = value;
  }

  /**
   * Gets the value of the 'id_transacao' field.
   * @return Id da transacao
   */
  public java.lang.String getIdTransacao() {
    return id_transacao;
  }

  /**
   * Sets the value of the 'id_transacao' field.
   * Id da transacao
   * @param value the value to set.
   */
  public void setIdTransacao(java.lang.String value) {
    this.id_transacao = value;
  }

  /**
   * Gets the value of the 'tipo_transacao' field.
   * @return Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
   */
  public java.lang.String getTipoTransacao() {
    return tipo_transacao;
  }

  /**
   * Sets the value of the 'tipo_transacao' field.
   * Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
   * @param value the value to set.
   */
  public void setTipoTransacao(java.lang.String value) {
    this.tipo_transacao = value;
  }

  /**
   * Creates a new Transferencia RecordBuilder.
   * @return A new Transferencia RecordBuilder
   */
  public static com.gm4c.tef.Transferencia.Builder newBuilder() {
    return new com.gm4c.tef.Transferencia.Builder();
  }

  /**
   * Creates a new Transferencia RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Transferencia RecordBuilder
   */
  public static com.gm4c.tef.Transferencia.Builder newBuilder(com.gm4c.tef.Transferencia.Builder other) {
    return new com.gm4c.tef.Transferencia.Builder(other);
  }

  /**
   * Creates a new Transferencia RecordBuilder by copying an existing Transferencia instance.
   * @param other The existing instance to copy.
   * @return A new Transferencia RecordBuilder
   */
  public static com.gm4c.tef.Transferencia.Builder newBuilder(com.gm4c.tef.Transferencia other) {
    return new com.gm4c.tef.Transferencia.Builder(other);
  }

  /**
   * RecordBuilder for Transferencia instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Transferencia>
    implements org.apache.avro.data.RecordBuilder<Transferencia> {

    /** tipo do evento: simulacao, efeticacao, externo */
    private java.lang.String evento;
    /** Codigo da agencia de origem */
    private int agencia_origem;
    /** Codigo da conta de origem */
    private int conta_origem;
    /** Dac da conta de origem */
    private int dv_origem;
    /** Codigo da agencia de destino */
    private int agencia_destino;
    /** Codigo da conta de destino */
    private int conta_destino;
    /** dac da conta de destino */
    private int dv_destino;
    /** Valor da Transferencia */
    private float valor;
    /** Senha para validar a transferencia */
    private java.lang.String senha;
    /** Id da transacao */
    private java.lang.String id_transacao;
    /** Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC */
    private java.lang.String tipo_transacao;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.gm4c.tef.Transferencia.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.evento)) {
        this.evento = data().deepCopy(fields()[0].schema(), other.evento);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agencia_origem)) {
        this.agencia_origem = data().deepCopy(fields()[1].schema(), other.agencia_origem);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.conta_origem)) {
        this.conta_origem = data().deepCopy(fields()[2].schema(), other.conta_origem);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dv_origem)) {
        this.dv_origem = data().deepCopy(fields()[3].schema(), other.dv_origem);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.agencia_destino)) {
        this.agencia_destino = data().deepCopy(fields()[4].schema(), other.agencia_destino);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.conta_destino)) {
        this.conta_destino = data().deepCopy(fields()[5].schema(), other.conta_destino);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dv_destino)) {
        this.dv_destino = data().deepCopy(fields()[6].schema(), other.dv_destino);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.valor)) {
        this.valor = data().deepCopy(fields()[7].schema(), other.valor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.senha)) {
        this.senha = data().deepCopy(fields()[8].schema(), other.senha);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.id_transacao)) {
        this.id_transacao = data().deepCopy(fields()[9].schema(), other.id_transacao);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tipo_transacao)) {
        this.tipo_transacao = data().deepCopy(fields()[10].schema(), other.tipo_transacao);
        fieldSetFlags()[10] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Transferencia instance
     * @param other The existing instance to copy.
     */
    private Builder(com.gm4c.tef.Transferencia other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.evento)) {
        this.evento = data().deepCopy(fields()[0].schema(), other.evento);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.agencia_origem)) {
        this.agencia_origem = data().deepCopy(fields()[1].schema(), other.agencia_origem);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.conta_origem)) {
        this.conta_origem = data().deepCopy(fields()[2].schema(), other.conta_origem);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.dv_origem)) {
        this.dv_origem = data().deepCopy(fields()[3].schema(), other.dv_origem);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.agencia_destino)) {
        this.agencia_destino = data().deepCopy(fields()[4].schema(), other.agencia_destino);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.conta_destino)) {
        this.conta_destino = data().deepCopy(fields()[5].schema(), other.conta_destino);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.dv_destino)) {
        this.dv_destino = data().deepCopy(fields()[6].schema(), other.dv_destino);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.valor)) {
        this.valor = data().deepCopy(fields()[7].schema(), other.valor);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.senha)) {
        this.senha = data().deepCopy(fields()[8].schema(), other.senha);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.id_transacao)) {
        this.id_transacao = data().deepCopy(fields()[9].schema(), other.id_transacao);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.tipo_transacao)) {
        this.tipo_transacao = data().deepCopy(fields()[10].schema(), other.tipo_transacao);
        fieldSetFlags()[10] = true;
      }
    }

    /**
      * Gets the value of the 'evento' field.
      * tipo do evento: simulacao, efeticacao, externo
      * @return The value.
      */
    public java.lang.String getEvento() {
      return evento;
    }

    /**
      * Sets the value of the 'evento' field.
      * tipo do evento: simulacao, efeticacao, externo
      * @param value The value of 'evento'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setEvento(java.lang.String value) {
      validate(fields()[0], value);
      this.evento = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'evento' field has been set.
      * tipo do evento: simulacao, efeticacao, externo
      * @return True if the 'evento' field has been set, false otherwise.
      */
    public boolean hasEvento() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'evento' field.
      * tipo do evento: simulacao, efeticacao, externo
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearEvento() {
      evento = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @return The value.
      */
    public java.lang.Integer getAgenciaOrigem() {
      return agencia_origem;
    }

    /**
      * Sets the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @param value The value of 'agencia_origem'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setAgenciaOrigem(int value) {
      validate(fields()[1], value);
      this.agencia_origem = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'agencia_origem' field has been set.
      * Codigo da agencia de origem
      * @return True if the 'agencia_origem' field has been set, false otherwise.
      */
    public boolean hasAgenciaOrigem() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'agencia_origem' field.
      * Codigo da agencia de origem
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearAgenciaOrigem() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @return The value.
      */
    public java.lang.Integer getContaOrigem() {
      return conta_origem;
    }

    /**
      * Sets the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @param value The value of 'conta_origem'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setContaOrigem(int value) {
      validate(fields()[2], value);
      this.conta_origem = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'conta_origem' field has been set.
      * Codigo da conta de origem
      * @return True if the 'conta_origem' field has been set, false otherwise.
      */
    public boolean hasContaOrigem() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'conta_origem' field.
      * Codigo da conta de origem
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearContaOrigem() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @return The value.
      */
    public java.lang.Integer getDvOrigem() {
      return dv_origem;
    }

    /**
      * Sets the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @param value The value of 'dv_origem'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setDvOrigem(int value) {
      validate(fields()[3], value);
      this.dv_origem = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'dv_origem' field has been set.
      * Dac da conta de origem
      * @return True if the 'dv_origem' field has been set, false otherwise.
      */
    public boolean hasDvOrigem() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'dv_origem' field.
      * Dac da conta de origem
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearDvOrigem() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @return The value.
      */
    public java.lang.Integer getAgenciaDestino() {
      return agencia_destino;
    }

    /**
      * Sets the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @param value The value of 'agencia_destino'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setAgenciaDestino(int value) {
      validate(fields()[4], value);
      this.agencia_destino = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'agencia_destino' field has been set.
      * Codigo da agencia de destino
      * @return True if the 'agencia_destino' field has been set, false otherwise.
      */
    public boolean hasAgenciaDestino() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'agencia_destino' field.
      * Codigo da agencia de destino
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearAgenciaDestino() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @return The value.
      */
    public java.lang.Integer getContaDestino() {
      return conta_destino;
    }

    /**
      * Sets the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @param value The value of 'conta_destino'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setContaDestino(int value) {
      validate(fields()[5], value);
      this.conta_destino = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'conta_destino' field has been set.
      * Codigo da conta de destino
      * @return True if the 'conta_destino' field has been set, false otherwise.
      */
    public boolean hasContaDestino() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'conta_destino' field.
      * Codigo da conta de destino
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearContaDestino() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'dv_destino' field.
      * dac da conta de destino
      * @return The value.
      */
    public java.lang.Integer getDvDestino() {
      return dv_destino;
    }

    /**
      * Sets the value of the 'dv_destino' field.
      * dac da conta de destino
      * @param value The value of 'dv_destino'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setDvDestino(int value) {
      validate(fields()[6], value);
      this.dv_destino = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'dv_destino' field has been set.
      * dac da conta de destino
      * @return True if the 'dv_destino' field has been set, false otherwise.
      */
    public boolean hasDvDestino() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'dv_destino' field.
      * dac da conta de destino
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearDvDestino() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'valor' field.
      * Valor da Transferencia
      * @return The value.
      */
    public java.lang.Float getValor() {
      return valor;
    }

    /**
      * Sets the value of the 'valor' field.
      * Valor da Transferencia
      * @param value The value of 'valor'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setValor(float value) {
      validate(fields()[7], value);
      this.valor = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'valor' field has been set.
      * Valor da Transferencia
      * @return True if the 'valor' field has been set, false otherwise.
      */
    public boolean hasValor() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'valor' field.
      * Valor da Transferencia
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearValor() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'senha' field.
      * Senha para validar a transferencia
      * @return The value.
      */
    public java.lang.String getSenha() {
      return senha;
    }

    /**
      * Sets the value of the 'senha' field.
      * Senha para validar a transferencia
      * @param value The value of 'senha'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setSenha(java.lang.String value) {
      validate(fields()[8], value);
      this.senha = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'senha' field has been set.
      * Senha para validar a transferencia
      * @return True if the 'senha' field has been set, false otherwise.
      */
    public boolean hasSenha() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'senha' field.
      * Senha para validar a transferencia
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearSenha() {
      senha = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'id_transacao' field.
      * Id da transacao
      * @return The value.
      */
    public java.lang.String getIdTransacao() {
      return id_transacao;
    }

    /**
      * Sets the value of the 'id_transacao' field.
      * Id da transacao
      * @param value The value of 'id_transacao'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setIdTransacao(java.lang.String value) {
      validate(fields()[9], value);
      this.id_transacao = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'id_transacao' field has been set.
      * Id da transacao
      * @return True if the 'id_transacao' field has been set, false otherwise.
      */
    public boolean hasIdTransacao() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'id_transacao' field.
      * Id da transacao
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearIdTransacao() {
      id_transacao = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'tipo_transacao' field.
      * Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
      * @return The value.
      */
    public java.lang.String getTipoTransacao() {
      return tipo_transacao;
    }

    /**
      * Sets the value of the 'tipo_transacao' field.
      * Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
      * @param value The value of 'tipo_transacao'.
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder setTipoTransacao(java.lang.String value) {
      validate(fields()[10], value);
      this.tipo_transacao = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'tipo_transacao' field has been set.
      * Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
      * @return True if the 'tipo_transacao' field has been set, false otherwise.
      */
    public boolean hasTipoTransacao() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'tipo_transacao' field.
      * Tipo de transacao, CC_CC, CC_CP, CP_CP, CP_CC
      * @return This builder.
      */
    public com.gm4c.tef.Transferencia.Builder clearTipoTransacao() {
      tipo_transacao = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Transferencia build() {
      try {
        Transferencia record = new Transferencia();
        record.evento = fieldSetFlags()[0] ? this.evento : (java.lang.String) defaultValue(fields()[0]);
        record.agencia_origem = fieldSetFlags()[1] ? this.agencia_origem : (java.lang.Integer) defaultValue(fields()[1]);
        record.conta_origem = fieldSetFlags()[2] ? this.conta_origem : (java.lang.Integer) defaultValue(fields()[2]);
        record.dv_origem = fieldSetFlags()[3] ? this.dv_origem : (java.lang.Integer) defaultValue(fields()[3]);
        record.agencia_destino = fieldSetFlags()[4] ? this.agencia_destino : (java.lang.Integer) defaultValue(fields()[4]);
        record.conta_destino = fieldSetFlags()[5] ? this.conta_destino : (java.lang.Integer) defaultValue(fields()[5]);
        record.dv_destino = fieldSetFlags()[6] ? this.dv_destino : (java.lang.Integer) defaultValue(fields()[6]);
        record.valor = fieldSetFlags()[7] ? this.valor : (java.lang.Float) defaultValue(fields()[7]);
        record.senha = fieldSetFlags()[8] ? this.senha : (java.lang.String) defaultValue(fields()[8]);
        record.id_transacao = fieldSetFlags()[9] ? this.id_transacao : (java.lang.String) defaultValue(fields()[9]);
        record.tipo_transacao = fieldSetFlags()[10] ? this.tipo_transacao : (java.lang.String) defaultValue(fields()[10]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Transferencia>
    WRITER$ = (org.apache.avro.io.DatumWriter<Transferencia>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Transferencia>
    READER$ = (org.apache.avro.io.DatumReader<Transferencia>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
