apiVersion: v1
kind: Service
metadata:
  name: cassandra-svc
  namespace: acad
  labels:
    name: cassandra
spec:
  ports:
  - port: 7000 
    name: porta1
    protocol: TCP
    targetPort: 7000
  - port: 9042
    name: porta2
    protocol: TCP
    targetPort: 9042
  selector:
    name: cassandra
