kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "gm4c-tef"
  namespace: acad
spec:
  selector:
    matchLabels: 
      name: "gm4c-tef"
  template: 
    metadata:
      labels:
        name: "gm4c-tef"      
    spec:
      containers:
        - name: "gm4c-tef"
          env:
            - name: "JAR_FILE"
              value: "/tmp/Gm4cTEF-0.0.1-SNAPSHOT.jar"
          image: "seberino/gm4c:2.2"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
          volumeMounts:
          - name: app-yml
            mountPath: /tmp/configmap/application.yml  
            subPath: application.yml        
      volumes:
        - name: app-yml
          configMap:
            name: tef-application
  replicas: 1 
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "gm4c-senha"
  namespace: acad
spec:
  selector:
    matchLabels: 
      name: "gm4c-senha"
  template: 
    metadata:
      labels:
        name: "gm4c-senha"      
    spec:
      containers:
        - name: "gm4c-senha"
          env:
            - name: "JAR_FILE"
              value: "/tmp/Gm4cSenha-0.0.1-SNAPSHOT.jar"
          image: "seberino/gm4c:2.2"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
          volumeMounts:
          - name: app-yml
            mountPath: /tmp/configmap/application.yml  
            subPath: application.yml        
      volumes:
        - name: app-yml
          configMap:
            name: senha-application
  replicas: 1 
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "gm4c-limite"
  namespace: acad
spec:
  selector:
    matchLabels: 
      name: "gm4c-limite"
  template: 
    metadata:
      labels:
        name: "gm4c-limite"      
    spec:
      containers:
        - name: "gm4c-limite"
          env:
            - name: "JAR_FILE"
              value: "/tmp/Gm4cLimite-0.0.1-SNAPSHOT.jar"
          image: "seberino/gm4c:2.2"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
          volumeMounts:
          - name: app-yml
            mountPath: /tmp/configmap/application.yml  
            subPath: application.yml        
      volumes:
        - name: app-yml
          configMap:
            name: limite-application
  replicas: 1 
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "gm4c-conta"
  namespace: acad
spec:
  selector:
    matchLabels: 
      name: "gm4c-conta"
  template: 
    metadata:
      labels:
        name: "gm4c-conta"      
    spec:
      containers:
        - name: "gm4c-conta"
          env:
            - name: "JAR_FILE"
              value: "/tmp/Gm4cConta-0.0.1-SNAPSHOT.jar"
          image: "seberino/gm4c:2.2"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
          volumeMounts:
          - name: app-yml
            mountPath: /tmp/configmap/application.yml  
            subPath: application.yml        
      volumes:
        - name: app-yml
          configMap:
            name: conta-application
  replicas: 1 
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "gm4c-springadmin"
  namespace: acad
spec:
  selector:
    matchLabels: 
      name: "gm4c-springadmin"
  template: 
    metadata:
      labels:
        name: "gm4c-springadmin"      
    spec:
      containers:
        - name: "gm4c-springadmin"
          env:
            - name: "JAR_FILE"
              value: "/tmp/Gm4cSpringAdmin-0.0.1-SNAPSHOT.jar"
          image: "seberino/gm4c:2.2"
          ports:
            - containerPort: 8080
              name: "porta1"
              protocol: TCP
  replicas: 1 
---
apiVersion: v1
kind: Service
metadata:
  name: tef
  namespace: acad
  labels:
    name: tef
spec:
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
  selector:
    name: gm4c-tef
---
apiVersion: v1
kind: Service
metadata:
  name: spring-admin-svc
  namespace: acad
  labels:
    name: spring-admin-svc
spec:
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
  selector:
    name: gm4c-springadmin
---
apiVersion: v1
kind: Service
metadata:
  name: limite
  namespace: acad
  labels:
    name: limite
spec:
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
  selector:
    name: gm4c-limite    
---
apiVersion: v1
kind: Service
metadata:
  name: senha
  namespace: acad
  labels:
    name: senha
spec:
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
  selector:
    name: gm4c-senha
---
apiVersion: v1
kind: Service
metadata:
  name: conta
  namespace: acad
  labels:
    name: conta
spec:
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
  selector:
    name: gm4c-conta
---
apiVersion: v1
kind: Service
metadata:
  name: tef-ext-svc
  namespace: acad
  labels:
    name: tef-ext-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    name: porta1
    protocol: TCP
    targetPort: 8080
    nodePort: 31009
  selector:
    name: gm4c-tef

