kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: "grafana"
spec:
  selector:
    matchLabels: 
      name: "grafana"
  template: 
    metadata:
      labels:
        name: "grafana"
    spec:
      containers:
        - name: "grafana"
          image: "grafana/grafana:latest"
          securityContext:
            privileged: true
          ports:
            - containerPort: 3000 
              name: "porta1"
          volumeMounts: 
          - mountPath: /tmp/grafana/grafana.yml
            name: grafana-setup
      volumes:
      - name: grafana-setup
        hostPath:
          path: /root/gm4c/Gm4cArtefatos/Grafana/grafana_dashboard_20200416.json
          type: File              
  replicas: 1 
